---
# tasks file for grafana
- name: Install grafana
  package:
    name: "{{ grafana_pkg }}"
    state: present

- name: Grafana configuration
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
