---
- name: Set up grafana
  hosts: prom
  gather_facts: true
  user: centos
  become: true
  vars_files:
    - ../ansible-environments/group_vars/grpvars.yml
    - ../ansible-environments/group_vars/all.yml

  roles:
    - grafana
