---
- name: Set up prometheus
  hosts: prom-01
  gather_facts: true
  user: centos
  become: true
  vars_files:
  - ../ansible-environments/group_vars/grpvars.yml
  - ../ansible-environments/group_vars/prometheus.yml

  roles:
    - prometheus
    - firewalld
